-- 3d-shop mock data. Images are hotlinked from Wikimedia Commons (open licenses); replace via Admin.

insert into public.shop3d_categories (slug, name, description, image_url, sort_order) values
('do-choi-in-3d', 'Đồ chơi in 3D', 'Đồ chơi khớp động, xe mô hình, đồ chơi giáo dục in bằng nhựa PLA an toàn.', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/CreativeTools.se_-_PackshotCreator_-_3D_printed_LEGO_toy_car_%284325785556%29.jpg/1280px-CreativeTools.se_-_PackshotCreator_-_3D_printed_LEGO_toy_car_%284325785556%29.jpg', 1),
('mo-hinh-figure', 'Mô hình & Figure', 'Rồng, chiến binh, mô hình kiến trúc in resin độ chi tiết cao.', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/CreativeTools.se_-_PackshotCreator_-_3D_printed_dragon_model.jpg/1280px-CreativeTools.se_-_PackshotCreator_-_3D_printed_dragon_model.jpg', 2),
('may-in-3d', 'Máy in 3D', 'Máy in FDM và resin cho người mới, xưởng nhỏ và kỹ sư.', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Prusa_i3_MK2.jpg', 3),
('vat-lieu-in', 'Sợi nhựa & Vật liệu', 'Filament PLA, PETG, ABS, TPU và resin chính hãng.', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/3D_printing_filament.jpg/1280px-3D_printing_filament.jpg', 4),
('phu-kien-linh-kien', 'Phụ kiện & Linh kiện', 'Đầu phun, bàn nhiệt, giá đỡ cuộn nhựa và dụng cụ hoàn thiện.', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d2/Hardened_Steel_3D_Printing_Nozzle.jpg/1280px-Hardened_Steel_3D_Printing_Nozzle.jpg', 5);

with c as (select slug, id from public.shop3d_categories)
insert into public.shop3d_products (slug, name, category_id, short_description, description, price, compare_at_price, stock, images, specs, is_featured)
select v.slug, v.name, c.id, v.short_description, v.description, v.price, v.compare_at_price, v.stock, v.images, v.specs::jsonb, v.is_featured
from (values
('rong-khop-dong-flexi', 'Rồng khớp động Flexi Dragon', 'mo-hinh-figure',
 'Rồng in liền khối, các khớp chuyển động mềm mại, không cần lắp ráp.',
 'Mẫu rồng khớp động được in liền một lần (print-in-place) bằng nhựa PLA lụa ánh kim. Mỗi đốt thân xoay linh hoạt, phù hợp làm đồ chơi giải trí, quà tặng hoặc trang trí bàn làm việc.',
 189000, 250000, 40,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Dragon_print_2.jpg/1280px-Dragon_print_2.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Dragon_print.jpg/1280px-Dragon_print.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Dragon_print_3.jpg/1280px-Dragon_print_3.jpg'],
 '[{"label":"Chất liệu","value":"PLA Silk ánh kim"},{"label":"Chiều dài","value":"30 cm"},{"label":"Công nghệ","value":"FDM, in liền khối"},{"label":"Độ dày lớp","value":"0.2 mm"},{"label":"Độ tuổi","value":"6+"}]', true),
('mo-hinh-rong-toothless', 'Mô hình rồng Toothless', 'mo-hinh-figure',
 'Mô hình rồng đen sơn tay, độ chi tiết cao.',
 'Mô hình rồng lấy cảm hứng từ phim hoạt hình, in resin độ phân giải cao và sơn hoàn thiện thủ công. Đế trưng bày đi kèm.',
 450000, null, 12,
 array['https://upload.wikimedia.org/wikipedia/commons/8/80/CSIRO_ScienceImage_1861_3D_Printed_Toothless_Dragon.jpg'],
 '[{"label":"Chất liệu","value":"Resin tiêu chuẩn"},{"label":"Chiều cao","value":"15 cm"},{"label":"Hoàn thiện","value":"Sơn tay, phủ mờ"},{"label":"Công nghệ","value":"MSLA resin"}]', true),
('rong-trang-tri-de-ban', 'Rồng trang trí để bàn', 'mo-hinh-figure',
 'Tượng rồng in 3D nguyên khối làm quà tặng.',
 'Tượng rồng tư thế đứng, bề mặt xử lý mịn, phù hợp trang trí kệ sách, bàn làm việc.',
 320000, 380000, 18,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/CreativeTools.se_-_PackshotCreator_-_3D_printed_dragon_model.jpg/1280px-CreativeTools.se_-_PackshotCreator_-_3D_printed_dragon_model.jpg'],
 '[{"label":"Chất liệu","value":"PLA+"},{"label":"Kích thước","value":"18 x 12 x 10 cm"},{"label":"Khối lượng","value":"160 g"}]', false),
('chien-binh-mini-tabletop', 'Chiến binh mini Tabletop 32mm', 'mo-hinh-figure',
 'Miniature cho board game, chưa sơn, sẵn sàng tô màu.',
 'Mẫu chiến binh tỉ lệ 32mm cho các trò chơi nhập vai trên bàn. In resin 8K, đã gỡ support và xử lý UV.',
 85000, null, 100,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/3d_printed_miniature_warrior_for_tabletop_gaming_on_a_white_background.jpg/1280px-3d_printed_miniature_warrior_for_tabletop_gaming_on_a_white_background.jpg'],
 '[{"label":"Tỉ lệ","value":"32 mm"},{"label":"Chất liệu","value":"Resin 8K"},{"label":"Tình trạng","value":"Chưa sơn"}]', false),
('xe-lap-ghep-mini', 'Xe lắp ghép mini', 'do-choi-in-3d',
 'Xe đồ chơi tương thích gạch lắp ghép phổ biến.',
 'Xe đồ chơi bánh xoay được, tương thích với gạch lắp ghép tiêu chuẩn. In PLA không độc hại, cạnh bo tròn an toàn cho bé.',
 129000, 159000, 60,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/CreativeTools.se_-_PackshotCreator_-_3D_printed_LEGO_toy_car_%284325785556%29.jpg/1280px-CreativeTools.se_-_PackshotCreator_-_3D_printed_LEGO_toy_car_%284325785556%29.jpg'],
 '[{"label":"Chất liệu","value":"PLA không độc hại"},{"label":"Kích thước","value":"10 x 6 x 5 cm"},{"label":"Độ tuổi","value":"4+"}]', true),
('voi-con-in-3d', 'Voi con in 3D', 'do-choi-in-3d',
 'Chú voi đáng yêu, quà tặng cho bé.',
 'Chú voi con in bằng PLA màu pastel, bề mặt mịn, cầm chắc tay. Có thể đặt in theo màu yêu cầu.',
 99000, null, 45,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Impression_3D_d%27un_elephant_%281%29.JPG/1280px-Impression_3D_d%27un_elephant_%281%29.JPG','https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Impression_3D_d%27un_elephant_%282%29.JPG/1280px-Impression_3D_d%27un_elephant_%282%29.JPG','https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Impression_3D_d%27un_elephant_%283%29.JPG/1280px-Impression_3D_d%27un_elephant_%283%29.JPG'],
 '[{"label":"Chất liệu","value":"PLA"},{"label":"Chiều cao","value":"8 cm"},{"label":"Màu","value":"Theo yêu cầu"}]', false),
('thuyen-benchy', 'Thuyền 3DBenchy sưu tầm', 'do-choi-in-3d',
 'Biểu tượng của cộng đồng in 3D.',
 'Con thuyền nhỏ 3DBenchy, mẫu thử kinh điển của dân in 3D. Bộ sưu tập nhiều màu, làm quà lưu niệm hoặc móc khóa.',
 49000, null, 200,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/3D_BENCHY.jpg/1280px-3D_BENCHY.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Benchy_and_fish_from_ouinche_v02.com_%2816588789944%29.jpg/1280px-Benchy_and_fish_from_ouinche_v02.com_%2816588789944%29.jpg'],
 '[{"label":"Chất liệu","value":"PLA"},{"label":"Kích thước","value":"6 x 3 x 4.8 cm"}]', false),
('boomerang-in-3d', 'Boomerang in 3D', 'do-choi-in-3d',
 'Boomerang bay trở lại, chơi ngoài trời.',
 'Boomerang 3 cánh thiết kế khí động học, in PETG dẻo dai chịu va đập.',
 79000, 99000, 80,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Red_Printed_Boomerang.jpg/1280px-Red_Printed_Boomerang.jpg'],
 '[{"label":"Chất liệu","value":"PETG"},{"label":"Sải cánh","value":"25 cm"},{"label":"Khối lượng","value":"55 g"}]', false),
('bo-ban-ghe-mini', 'Bộ bàn ghế mini', 'do-choi-in-3d',
 'Nội thất tí hon cho nhà búp bê.',
 'Bộ bàn và 4 ghế tỉ lệ 1:12 cho nhà búp bê hoặc diorama.',
 115000, null, 30,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/CreativeTools.se_-_PackshotCreator_-_3D_printed_table_and_chairs_%284325785386%29.jpg/1280px-CreativeTools.se_-_PackshotCreator_-_3D_printed_table_and_chairs_%284325785386%29.jpg'],
 '[{"label":"Tỉ lệ","value":"1:12"},{"label":"Số chi tiết","value":"5"},{"label":"Chất liệu","value":"PLA"}]', false),
('mo-hinh-nha-mini', 'Mô hình nhà mini', 'mo-hinh-figure',
 'Mô hình kiến trúc in màu toàn phần.',
 'Mô hình ngôi nhà in công nghệ in bột màu toàn phần, phù hợp sa bàn, quà tặng kiến trúc sư.',
 550000, null, 6,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/CreativeTools.se_-_PackshotCreator_-_ZPrinter_-_3D_print_-_House_miniature_%284458992163%29.jpg/1280px-CreativeTools.se_-_PackshotCreator_-_ZPrinter_-_3D_print_-_House_miniature_%284458992163%29.jpg'],
 '[{"label":"Công nghệ","value":"Binder jetting màu"},{"label":"Kích thước","value":"12 x 10 x 9 cm"}]', false),
('may-in-prusa-i3-mk2', 'Máy in 3D Prusa i3 MK2', 'may-in-3d',
 'Máy in FDM huyền thoại, ổn định, dễ nâng cấp.',
 'Prusa i3 MK2 với bàn nhiệt cân bằng tự động, khung nhôm chắc chắn. Lựa chọn tin cậy cho người mới và xưởng nhỏ.',
 15900000, 17500000, 5,
 array['https://upload.wikimedia.org/wikipedia/commons/0/01/Prusa_i3_MK2.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Prusa_i3_-_RepRap_3D_printer_printing.jpg/1280px-Prusa_i3_-_RepRap_3D_printer_printing.jpg'],
 '[{"label":"Công nghệ","value":"FDM"},{"label":"Khổ in","value":"250 x 210 x 200 mm"},{"label":"Đầu phun","value":"0.4 mm"},{"label":"Nhiệt độ đầu phun tối đa","value":"300 °C"},{"label":"Nhiệt độ bàn tối đa","value":"120 °C"},{"label":"Độ phân giải lớp","value":"0.05 - 0.35 mm"},{"label":"Vật liệu hỗ trợ","value":"PLA, PETG, ABS, ASA, TPU"},{"label":"Kết nối","value":"USB, thẻ SD"},{"label":"Bảo hành","value":"12 tháng"}]', true),
('may-in-prusa-i3-khung-kim-loai', 'Máy in 3D i3 khung kim loại', 'may-in-3d',
 'Khung thép cứng vững, in nhanh ít rung.',
 'Phiên bản i3 khung kim loại nguyên tấm, giảm rung khi in tốc độ cao, phù hợp chạy liên tục.',
 8900000, null, 8,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Prusa_i3_with_metal_frame.jpg/1280px-Prusa_i3_with_metal_frame.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Prusa_i3_metal_frame.jpg/1280px-Prusa_i3_metal_frame.jpg'],
 '[{"label":"Công nghệ","value":"FDM"},{"label":"Khổ in","value":"200 x 200 x 180 mm"},{"label":"Khung","value":"Thép tấm 6 mm"},{"label":"Đầu phun","value":"0.4 mm"},{"label":"Bảo hành","value":"12 tháng"}]', false),
('may-in-delta-khong-lo', 'Máy in 3D Delta khổ lớn', 'may-in-3d',
 'Khổ in cao, tốc độ nhanh cho chi tiết lớn.',
 'Máy in kiểu Delta với chiều cao in vượt trội, lý tưởng cho bình hoa, mô hình cao và sản xuất nhỏ.',
 24500000, null, 2,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Large_delta-style_3D_printer.jpg/1280px-Large_delta-style_3D_printer.jpg'],
 '[{"label":"Công nghệ","value":"FDM Delta"},{"label":"Khổ in","value":"Ø 350 x 800 mm"},{"label":"Tốc độ tối đa","value":"300 mm/s"},{"label":"Bảo hành","value":"12 tháng"}]', false),
('may-in-resin-halot-x1', 'Máy in Resin Halot-X1', 'may-in-3d',
 'In resin 8K, chi tiết sắc nét cho figure.',
 'Máy in resin màn hình đơn sắc độ phân giải cao, nguồn sáng tích hợp đồng đều, kết nối Wi-Fi điều khiển từ xa.',
 12900000, 13900000, 4,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Halot-X1.jpg/1280px-Halot-X1.jpg'],
 '[{"label":"Công nghệ","value":"MSLA Resin"},{"label":"Màn hình","value":"8K đơn sắc"},{"label":"Khổ in","value":"192 x 120 x 200 mm"},{"label":"Độ chính xác XY","value":"25 µm"},{"label":"Kết nối","value":"Wi-Fi, USB"},{"label":"Bảo hành","value":"12 tháng"}]', true),
('kit-may-in-ender-diy', 'Bộ kit máy in Ender tự lắp', 'may-in-3d',
 'Bộ kit DIY giá tốt, học cơ khí và điện tử.',
 'Bộ kit máy in FDM tự lắp ráp, kèm hướng dẫn tiếng Việt. Phù hợp học sinh, sinh viên muốn hiểu sâu nguyên lý máy in 3D.',
 4290000, 4990000, 15,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Ender_3x_3D%E5%8D%B0%E8%A1%A8%E6%A9%9F_%E5%A5%97%E4%BB%B6_-_49804177743.jpg/1280px-Ender_3x_3D%E5%8D%B0%E8%A1%A8%E6%A9%9F_%E5%A5%97%E4%BB%B6_-_49804177743.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Ender_3x_3D%E5%8D%B0%E8%A1%A8%E6%A9%9F_%E5%A5%97%E4%BB%B6_-_49805040652.jpg/1280px-Ender_3x_3D%E5%8D%B0%E8%A1%A8%E6%A9%9F_%E5%A5%97%E4%BB%B6_-_49805040652.jpg'],
 '[{"label":"Công nghệ","value":"FDM"},{"label":"Khổ in","value":"220 x 220 x 250 mm"},{"label":"Thời gian lắp","value":"2 - 3 giờ"},{"label":"Bảo hành","value":"6 tháng"}]', false),
('soi-petg-1kg', 'Sợi nhựa PETG 1.75mm 1kg', 'vat-lieu-in',
 'PETG bền, dẻo, chịu nhiệt tốt hơn PLA.',
 'Cuộn sợi PETG đường kính 1.75mm sai số ±0.02mm, hút chân không chống ẩm.',
 290000, null, 120,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/1_kg_petg_filament_in_packaging.jpg/1280px-1_kg_petg_filament_in_packaging.jpg'],
 '[{"label":"Đường kính","value":"1.75 mm ± 0.02"},{"label":"Khối lượng","value":"1 kg"},{"label":"Nhiệt độ in","value":"230 - 250 °C"},{"label":"Nhiệt độ bàn","value":"70 - 85 °C"}]', false),
('soi-pla-nhieu-mau', 'Sợi nhựa PLA 1.75mm nhiều màu', 'vat-lieu-in',
 'PLA dễ in, nhiều màu sắc, thân thiện môi trường.',
 'Sợi PLA phân hủy sinh học, ít cong vênh, phù hợp mọi máy in FDM phổ thông.',
 239000, 270000, 200,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/3D_printing_filament.jpg/1280px-3D_printing_filament.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/3D_Printing_Filament_789.jpg/1280px-3D_Printing_Filament_789.jpg'],
 '[{"label":"Đường kính","value":"1.75 mm"},{"label":"Khối lượng","value":"1 kg"},{"label":"Nhiệt độ in","value":"190 - 220 °C"},{"label":"Màu","value":"12 màu"}]', true),
('soi-nhua-refill-giay', 'Sợi nhựa refill lõi giấy', 'vat-lieu-in',
 'Cuộn refill không lõi nhựa, giảm rác thải.',
 'Cuộn sợi dạng refill dùng với lõi tái sử dụng, tiết kiệm và thân thiện môi trường.',
 219000, null, 90,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Filament_cardboard_plastic_refill_2.jpg/1280px-Filament_cardboard_plastic_refill_2.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Filament_cardboard_plastic_refill_1.jpg/1280px-Filament_cardboard_plastic_refill_1.jpg'],
 '[{"label":"Đường kính","value":"1.75 mm"},{"label":"Khối lượng","value":"1 kg"},{"label":"Lõi","value":"Giấy tái chế"}]', false),
('dau-phun-thep-cung', 'Đầu phun thép cứng 0.4mm', 'phu-kien-linh-kien',
 'In được sợi carbon, glow-in-the-dark không mòn.',
 'Đầu phun thép tôi cứng chống mài mòn, chuẩn ren M6, tương thích phần lớn hotend phổ biến.',
 159000, null, 150,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d2/Hardened_Steel_3D_Printing_Nozzle.jpg/1280px-Hardened_Steel_3D_Printing_Nozzle.jpg'],
 '[{"label":"Vật liệu","value":"Thép tôi cứng"},{"label":"Đường kính","value":"0.4 mm"},{"label":"Ren","value":"M6"},{"label":"Nhiệt độ tối đa","value":"500 °C"}]', false),
('gia-do-cuon-nhua', 'Giá đỡ cuộn nhựa đa năng', 'phu-kien-linh-kien',
 'Giá đỡ có ổ bi, nhả sợi trơn tru.',
 'Giá đỡ cuộn nhựa đứng độc lập, có ổ bi giảm ma sát, vừa mọi cuộn 0.5 - 3 kg.',
 135000, 169000, 70,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Universal_stand-alone_filament_spool_holder_%28Fully_3D-printable%29_v04.jpg/1280px-Universal_stand-alone_filament_spool_holder_%28Fully_3D-printable%29_v04.jpg','https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Universal_stand-alone_filament_spool_holder_%28Fully_3D-printable%29_v07.jpg/1280px-Universal_stand-alone_filament_spool_holder_%28Fully_3D-printable%29_v07.jpg'],
 '[{"label":"Tải trọng","value":"Tối đa 3 kg"},{"label":"Ổ bi","value":"608ZZ"},{"label":"Chất liệu","value":"PETG"}]', false),
('cum-dau-dun-extruder', 'Cụm đầu đùn Extruder i3', 'phu-kien-linh-kien',
 'Cụm extruder lắp sẵn thay thế cho máy i3.',
 'Cụm đầu đùn đã lắp ráp hoàn chỉnh, bánh răng giảm tốc, lực kéo sợi mạnh, thay thế nhanh cho dòng i3.',
 690000, null, 20,
 array['https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Prusa_i3_Printer_-_Assembled_extruder.jpg/1280px-Prusa_i3_Printer_-_Assembled_extruder.jpg'],
 '[{"label":"Tương thích","value":"Dòng i3"},{"label":"Tỉ số truyền","value":"3:1"},{"label":"Sợi hỗ trợ","value":"1.75 mm"}]', false)
) as v (slug, name, category_slug, short_description, description, price, compare_at_price, stock, images, specs, is_featured)
join c on c.slug = v.category_slug;

insert into public.shop3d_settings (key, value) values
('site', '{"name":"Print3D Shop","tagline":"Đồ chơi in 3D & máy in 3D chính hãng","description":"Cửa hàng đồ chơi in 3D, mô hình, máy in 3D, sợi nhựa và phụ kiện tại Việt Nam. Giao hàng toàn quốc, bảo hành chính hãng.","logo_url":""}'),
('contact', '{"phone":"0900000000","email":"hello@print3d.vn","address":"123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh","zalo":"0900000000","facebook":"","hours":"8:00 - 21:00 mỗi ngày"}'),
('hero', '{"eyebrow":"In 3D cho mọi ý tưởng","title":"Biến ý tưởng thành vật thể thật","subtitle":"Đồ chơi in 3D độc đáo, máy in 3D chính hãng và vật liệu chất lượng cao — giao nhanh toàn quốc.","cta_label":"Khám phá sản phẩm","cta_href":"/san-pham","image_url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Prusa_i3_-_RepRap_3D_printer_printing.jpg/1280px-Prusa_i3_-_RepRap_3D_printer_printing.jpg"}'),
('banners', '[{"title":"Máy in 3D giảm đến 15%","subtitle":"Tặng kèm 2 cuộn PLA khi mua máy trong tháng này","href":"/san-pham?danh-muc=may-in-3d","image_url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/3D_printer_farm_at_Hackerspace_Wroc%C5%82aw.jpg/1280px-3D_printer_farm_at_Hackerspace_Wroc%C5%82aw.jpg"},{"title":"Đồ chơi in 3D cho bé","subtitle":"Nhựa PLA an toàn, thiết kế độc quyền","href":"/san-pham?danh-muc=do-choi-in-3d","image_url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Altrum-3D_prints.jpg/1280px-Altrum-3D_prints.jpg"}]'),
('sections', '{"show_categories":true,"show_featured":true,"show_banners":true,"show_new":true,"show_highlights":true,"featured_title":"Sản phẩm nổi bật","new_title":"Hàng mới về","highlights":[{"title":"Giao hàng toàn quốc","text":"Miễn phí vận chuyển cho đơn từ 1.000.000đ"},{"title":"Bảo hành chính hãng","text":"Máy in bảo hành 12 tháng, đổi mới 7 ngày"},{"title":"Hỗ trợ kỹ thuật","text":"Hướng dẫn cài đặt, cân chỉnh máy miễn phí"},{"title":"In theo yêu cầu","text":"Nhận in mô hình, quà tặng theo file của bạn"}]}'),
('shipping', '{"flat_fee":30000,"free_threshold":1000000}'),
('bank', '{"bank_name":"Vietcombank","account_number":"0000000000","account_name":"PRINT3D SHOP"}');
